################################################################
# Elasticsearch node types.
#
# specific types for Elasticsearch.
# these types are mapped to scripts that are responsible
# for the lifecycle operation.
################################################################
tosca_definitions_version: cloudify_dsl_1_1

plugins:
  elasticsearch:
    executor: host_agent
    source: https://github.com/kemiz/cloudify-elasticsearch-plugin/archive/3.2.1.zip

node_types:

  elasticsearch.nodes.Elasticsearch:
    derived_from: cloudify.nodes.ServiceInstaller
    properties:
      service_name:
        default: 'elasticsearch'
      version:
        default: '1.7.1'
      config:
        default:
          package_list:
            - 'openjdk-7-jdk'
#            - 'https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.noarch.rpm'
            - 'https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.deb'
      es_config:
        default:
          api_port: 9200
          cluster_port: 9300

relationships:
  connected_to_elasticsearch:
    derived_from: cloudify.relationships.connected_to
